version: "3.8"

services:
  db:
    image: postgres:15
    container_name: spierfit-db
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/postgresql/data


  web:
    build: .
    container_name: spierfit-web
    depends_on:
      - db
      - api
      - redis
    env_file:
      - .env.production
    environment:
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
    ports:
      - "3000:3000"

  api:
    build:
      context: ../fastapi_app_esp32_data_processor
    container_name: fastapi-api
    expose:
      - "8000"

  redis:
    image: redis:7
    container_name: spierfit-redis



volumes:
  db_data:
