development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: spierfit_app_development

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: spierfit_app_production
