service: spierfit

image: andresalatalima/spierfit

servers:
  web:
    hosts:
      - 138.201.152.48

proxy:
  ssl: true
  host: spierfit.com,www.spierfit.com
  app_port: 3000

registry:
  username: andresalatalima
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true

  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - POSTGRES_PASSWORD
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: root

volumes:
  - "./storage:/rails/storage"

accessories:
  db:
    image: postgres:15
    host: 138.201.152.48
    env:
      clear:
        POSTGRES_DB: spierfit_production
        POSTGRES_USER: postgres
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7
    host: 138.201.152.48
    directories:
      - data:/data
