---
- Máquina Smith
- Máquina de Supino Horizontal
- Máquina de Supino Inclinado
- Máquina de Supino Declinado
- Peck Deck
- Máquina de Reverse Fly
- Barra Fixa
- Paralelas
- Cross-Over Polia
- Estação de Puxada Alta
- Máquina de Pull-Down
- Máquina de Remada
- Remada Cavalinho (T-bar Row)
- Plataforma de Pull-Over
- Máquina de Desenvolvimento de Ombros
- Máquina de Elevação Lateral
- Máquina de Elevação Frontal
- Máquina de Encolhimento de Ombros
- Máquina de Rosca Scott
- Máquina de Rosca Direta
- Máquina de Rosca Concentrada
- Máquina de Tríceps Pulley
- Máquina de Extensão de Punho
- Leg Press
- Máquina de Agachamento Hack
- Cadeira Extensora
- Mesa Flexora
- Cadeira Flexora
- Máquina Adutora
- Máquina Abdutora
- Máquina de Elevação Pélvica (Hip Thrust)
- Máquina de Gêmeos em Pé
- Máquina de Gêmeos Sentado
- Máquina de Extensão Lombar
- Máquina de Glúteos
- Máquina de Rosca Nórdica
- Máquina de Abdominal Crunch
- Máquina de Abdominal Oblíquo
- Máquina de Ab Coaster
